apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    k8s-app: app1
    k8s-project: project1

patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: project1
  target:
    kind: Deployment
    labelSelector: "k8s-app=app"
- patch: |-
    - op: replace
      path: /metadata/name
      value: app1
  target:
    kind: Deployment
    labelSelector: "k8s-app=app"

- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: app1
  target:
    kind: Deployment
    labelSelector: "k8s-app=app"
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: app1:v0.0.0
  target:
    kind: Deployment
    labelSelector: "k8s-app=app"